#!/bin/bash
# By Brielle Bruns <bruns@2mbit.com>
# URL: http://www.sosdg.org/freestuff/firewall
# License: GPLv3
#
#    Copyright (C) 2009 - 2010  Brielle Bruns
#    Copyright (C) 2009 - 2010  The Summit Open Source Development Group
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

CONFIGTOOL_VER="0.1"

WHIPTAIL="/usr/bin/whiptail"
TMPCONFIG=`mktemp`



# These are string variables
WELCOME_HEAD="Welcome to the Firewall/SOSDG Config Tool v${CONFIGTOOL_VER}"
WELCOME_BODY="This tool is a quick way to do a basic setup of the firewall script.
				The results of this tool will be output to a file of your choosing at
				the end of configuration.\nContinue?"
if [ ! -x $WHIPTAIL ]; then
	echo "Error: please make sure you have whiptail installed, and the WHIPTAIL variable 
		is set correctly in the tool."
	exit 1
fi

if ! ( $WHIPTAIL --yesno "${WELCOME_MSG}\n${WELCOME_BODY}" 12 60 --no-button "Quit" ); then
	echo "Quitting config tool."
	exit 1
fi