#!/bin/bash
echo "This script converts certain aspects of old config files, such"
echo "as renamed variables to the new variable names.  It is NOT foolproof"
echo "so please check your config files afterwards."

sed -e 's/IPV6FORWARD/IPV6_FORWARD/' \
	-e 's/IPV6CONNTRACK/IPV6_CONNTRACK/' \
	-e 's/IPV6BLOCKINCOMING/IPV6_BLOCKINCOMING/' \
	-e 's/IPv6_MARK/IPV6_MARK/' \
	-e 's/BLOCKEDIPV6/IPV6_BLOCKED/' \
	-e 's/CLAMPMSSIPV6/IPV6_CLAMPMSS/' \
	-e 's/IPV6INT/IPV6_INT/' \
	-e 's/IPV6LAN/IPV6_LAN/' \
	-e 's/IPV6TRUSTED/IPV6_TRUSTED/' \
	-e 's/IPV6TCP/IPV6_TCPPORTS/' \
	-e 's/IPV6UDP/IPV6_UDPPORTS/' \
	-e 's/IPV6FORWARDRANGE/IPV6_FORWARDRANGE/' \
	-e 's/IPV6ROUTEDCLIENTBLOCK/IPV6_ROUTEDCLIENTBLOCK/' options >> options.new

mv options options.bak
mv options.new options
